#!/bin/bash

export S="$(cd $(dirname ${BASH_SOURCE[0]}); pwd)"

if [ "$0" != "${BASH_SOURCE[0]}" ]; then
    PATH="$S:$PATH"
    alias br="./run build && ./run run"
    return
fi

if [ "$1" == "project" ]; then

    mkdir -p Project
    cd Project

    cmake -G Ninja ..

elif [ "$1" == "build" ]; then

    cmake --build Project

elif [ "$1" == "run" ]; then

    Project/dots

elif [ "$1" == "reset" ]; then

    rm -r Project

fi