name: Run

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true

            matrix:
                os: [ubuntu-latest, windows-latest]
                build_type: [Release]
                c_compiler: [clang, cl]
                cmake_preset: [vs, ninja]
                include:
                    -   os: windows-latest
                        c_compiler: cl
                        cpp_compiler: cl
                        cmake_preset: vs
                    -   os: ubuntu-latest
                        c_compiler: clang
                        cpp_compiler: clang++
                        cmake_preset: ninja
                exclude:
                    -   os: windows-latest
                        c_compiler: clang
                        cmake_preset: ninja
                    -   os: ubuntu-latest
                        c_compiler: cl
                        cmake_preset: vs

        steps:
        -   uses: actions/checkout@v3

        -   name: Setup
            run: ./run.sh setup

        -   name: Project
            run: ./run.sh project ${{ matrix.cmake_preset }}

        -   name: Build
            run: ./run.sh build ${{ matrix.cmake_preset }}

        -   name: Test
            run: ./run.sh test ${{ matrix.cmake_preset }}
