name: Run

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false

            matrix:
                os: [ubuntu-latest, windows-latest]
                cmake_preset: [vs, ninja]
                include:
                    -   os: windows-latest
                        cmake_preset: vs
                    -   os: ubuntu-latest
                        cmake_preset: ninja
                exclude:
                    -   os: windows-latest
                        cmake_preset: ninja
                    -   os: ubuntu-latest
                        cmake_preset: vs

        steps:
        -   uses: actions/checkout@v3

        -   name: Setup
            shell: bash
            run: chmod a+x run.sh && ./run.sh setup

        -   name: Project
            shell: bash
            run: ./run.sh project ${{ matrix.cmake_preset }}

        -   name: Build
            shell: bash
            run: ./run.sh build ${{ matrix.cmake_preset }}

        -   name: Test
            shell: bash
            run: ./run.sh test ${{ matrix.cmake_preset }}
